### ISSUE TITLE
Is this still under active dev? [MPS on non-Volta]

### ISSUE THREAD

**Issue by singlecheeze** [kuartis/kuartis-virtual-gpu-device-plugin#2]
Hello repo maintainers!

I was wondering if this project is being maintained? If so, please see the thread here: https://github.com/NVIDIA/gpu-operator/issues/420#issuecomment-1315131669

I have no idea where the issue is coming from. I am running on OpenShift 4.11.12 (kubernetes 1.24.6), with the latest Nvidia Operator.

**Comment by ghokun** [comment]
Hello, we are actively using it in one project.

One thing we have different is we are using RKE and have docker runtime. We are exposing vGPU metrics by matching pids with containers. To do that we are using docker socket. Would that be your issue? Since you are using Openshift and as far as I remember it uses a different runtime, namely `cri-o`.

**Comment by ghokun** [comment]
One more thing to add: We used [T4 gpus](https://www.techpowerup.com/gpu-specs/tesla-t4.c3316) which are turing architecture.
